/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmacia_san_antonio;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import login.RegistroUsuario;

/**
 *
 * @author frix4
 */
public class Menu extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        this.pintarimagen(this.logo, "C:\\Users\\frix4\\Documentos\\NetBeansProjects\\Farmacia_san_antonio\\src\\imagenes\\logo.png");
        this.pintarimagenB(this.Producto, "C:\\Users\\frix4\\Documentos\\NetBeansProjects\\Farmacia_san_antonio\\src\\imagenes\\inventario.png");
        this.pintarimagenB(this.Grafica, "C:\\Users\\frix4\\Documentos\\NetBeansProjects\\Farmacia_san_antonio\\src\\imagenes\\graficos.png");
        this.pintarimagenB(this.nose, "C:\\Users\\frix4\\Documentos\\NetBeansProjects\\Farmacia_san_antonio\\src\\imagenes\\usuarios-medicos.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        nose = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        Producto = new javax.swing.JButton();
        Grafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 118, 68));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 240, 50));

        usuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(9, 118, 68));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("Nuevo usuario");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, 40));

        modificar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(9, 118, 68));
        modificar.setText("Gestion de producto");
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 150, 30));

        estado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(9, 118, 68));
        estado.setText("Reporte y analisis");
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        nose.setBackground(new java.awt.Color(255, 255, 255));
        nose.setForeground(new java.awt.Color(9, 118, 68));
        nose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noseMouseClicked(evt);
            }
        });
        jPanel1.add(nose, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 130));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 80));

        Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoMouseClicked(evt);
            }
        });
        jPanel1.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 130));

        Grafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GraficaMouseClicked(evt);
            }
        });
        jPanel1.add(Grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 140, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noseMouseClicked
        RegistroUsuario ventanaRegistro = new RegistroUsuario(); // Crear instancia
    ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_noseMouseClicked

    private void ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoMouseClicked
        
    }//GEN-LAST:event_ProductoMouseClicked

    private void GraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraficaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GraficaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
private void pintarimagen(JLabel lbl, String ruta){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(
            this.imagen.getImage().getScaledInstance(
                    lbl.getWidth(), 
                    lbl.getHeight(), 
                    Image.SCALE_DEFAULT));
    lbl.setIcon(this.icono);
    }
private void pintarimagenB(JButton lbl, String ruta){
    this.imagen = new ImageIcon(ruta);
    this.icono = new ImageIcon(
            this.imagen.getImage().getScaledInstance(
                    lbl.getWidth(), 
                    lbl.getHeight(), 
                    Image.SCALE_DEFAULT));
    lbl.setIcon(this.icono);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Grafica;
    private javax.swing.JButton Producto;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel modificar;
    private javax.swing.JButton nose;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
